Mikolaslorant
wolox-training/ml-net-core pull request #1
Opened 2018-08-08 18:34 UTC by mikolaslorant

## Summary

## Screenshot

## Trello card

2018-08-09 01:15 UTC, FrankIglesias requested changes

2018-08-09 01:15 UTC, FrankIglesias commented on index.html
> +
delete this line and indent html tag

2018-08-09 01:15 UTC, FrankIglesias commented
Change the name of the Pull Request for something more descriptive

2018-08-10 12:02 UTC, mikolaslorant commented
Already corrected the requested changes.

2018-08-10 18:33 UTC, FrankIglesias approved these changes

2018-08-10 18:46 UTC, merged