Edit Movie, Movie Details, Delete Movie and Movie List
wolox-training/ml-net-core pull request #11
Opened 2018-08-29 13:21 UTC by mikolaslorant

## Summary 
-Added Edit movie option.
-Added Movie Deletion.
-Added details view.
-Added movie list.

## Trello card

-[https://trello.com/c/UdHt1B5d/29-lista-de-pel%C3%ADculas](url) (list)
-[https://trello.com/c/bw7oqLdD/8-edici%C3%B3n](url) (editar)
-[https://trello.com/c/A7AEPx9N/10-detalle-y-borrado](url) (borrado y detalles)

## Screenshot
Delete Movie
![deletemovie](https://user-images.githubusercontent.com/28982362/44790217-2ed47900-ab75-11e8-8757-b5ef6ad5f705.png)

Edit Movie
![editmovie](https://user-images.githubusercontent.com/28982362/44790218-2ed47900-ab75-11e8-817f-2e48649900d4.png)

Movie Details 
![moviedetails](https://user-images.githubusercontent.com/28982362/44790219-2ed47900-ab75-11e8-95d6-dde7adf68aaa.png)

Movie List
![movielist](https://user-images.githubusercontent.com/28982362/44790220-2f6d0f80-ab75-11e8-9534-6454577d53c4.png)

2018-08-30 22:13 UTC, gussiciliano requested changes

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
this is cool, but, it will better use a try catch and make it this with exceptions

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
tell me if you don't know how use exceptions on this case :)

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +        public IActionResult DeleteConfirmed(int id)
this is really cool :)

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +                return NotFound();
same as before

2018-08-30 22:13 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +        public IActionResult Details(int? id)
this method is like Edit method, it will be great abstract the similar code to a helper method

2018-08-30 22:13 UTC, gussiciliano commented on src/Views/HelloWorld/Details.cshtml
> +
fix this space

2018-08-30 22:13 UTC, gussiciliano commented on src/Views/HelloWorld/Details.cshtml
> +    <li> Title: @Html.DisplayFor(model => model.Title)</li>
add localization for all of this words

2018-08-31 13:57 UTC, mikolaslorant commented
Already corrected requested changes.

2018-08-31 15:53 UTC, gussiciliano approved these changes

2018-08-31 16:54 UTC, merged