Tech and title cards
wolox-training/ml-net-core pull request #2
Opened 2018-08-10 14:19 UTC by mikolaslorant

## Summary
-Added tech component.
-Added title component.
-Flexing for tech components.

## Screenshot
![screenshot from 2018-08-10 11-18-42](https://user-images.githubusercontent.com/28982362/43962883-332e579a-9c8f-11e8-8b81-df570e383747.png)

## Trello Card
-Tecnología
-Page Titles

2018-08-10 18:40 UTC, FrankIglesias requested changes

2018-08-10 18:40 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/react_icon.svg" alt="React logo"></img>
<img ...... />

2018-08-10 18:40 UTC, FrankIglesias commented on index.html
> +
delete this two lines

2018-08-10 18:40 UTC, FrankIglesias commented on scss/application.scss
> +.center-content {
move this to a layout scss

2018-08-10 18:40 UTC, FrankIglesias commented on scss/styles.scss
> +$blue: #00ADEE;
move this to colors.scss file

2018-08-10 18:40 UTC, FrankIglesias commented on scss/styles.scss
> +$text-big: 24px;
move this to a text file

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +
delete this line

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  left: 8px;
delete this

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  top: 8px;
and this

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  position:relative;
add space before 'relative'

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +.tech:before {
nest this inside tech

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  border-radius: inherit;
why this?

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +
delete this line

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +}
add a z-index prop

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  max-height: 100%;
delete this

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  width: 100px;
only fix one axis... i'd recommend only width size

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> + font-family: 'Roboto';
define this font-family in a more generic element, like body

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  font-family: 'Roboto';
this is unnesesary

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +
delete this line

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  justify-content: flex-start;
this is the default prop

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  flex-direction: row;
same

2018-08-10 18:40 UTC, FrankIglesias commented on scss/tech.scss
> +  align-content: flex-start;
same

2018-08-10 18:40 UTC, FrankIglesias commented on scss/titles.scss
> +
delete line

2018-08-10 18:40 UTC, FrankIglesias commented on scss/titles.scss
> +  background: url(assets/images/triangle.svg);
i think you missed the comma

2018-08-10 18:40 UTC, FrankIglesias commented on scss/titles.scss
> +.title:before {
nest this class into title

2018-08-10 18:40 UTC, FrankIglesias commented on scss/titles.scss
> +  margin-top:10px;
add a space before 10px

2018-08-10 18:40 UTC, FrankIglesias commented on scss/titles.scss
> +  margin-left: 15px;
use a shorthand for margins

2018-08-10 19:30 UTC, mikolaslorant commented
Already corrected changes

2018-08-14 01:27 UTC, FrankIglesias requested changes

2018-08-14 01:27 UTC, FrankIglesias commented on scss/tech.scss
> +  display:flex;
add space after comma

2018-08-14 01:28 UTC, FrankIglesias commented on scss/titles.scss
> +    content:'';
same

2018-08-15 12:09 UTC, mikolaslorant commented
Corrected new requested changes

2018-08-15 14:10 UTC, FrankIglesias approved these changes

2018-08-15 14:23 UTC, merged