Layout and transitions cards
wolox-training/ml-net-core pull request #3
Opened 2018-08-10 16:50 UTC by mikolaslorant

##Summary
-Corrected title decorations from previous pr.
-Added transitions on hover over tech components.
-Added text and missing tech components to complete layout (Polymer, Angular, etc.)
-Corrected font to Roboto.
-Layout padding and margin adjustment.
-Missing some text characters because of 404 on trello card link.

##Screenshot
![screenshot from 2018-08-10 13-48-44](https://user-images.githubusercontent.com/28982362/43970514-40586cac-9ca4-11e8-822f-7ae69406e389.png)
![screenshot from 2018-08-10 13-49-01](https://user-images.githubusercontent.com/28982362/43970520-43c7c496-9ca4-11e8-8c54-6d7298fda467.png)

##Trello card
-Layout.
-Transitions

2018-08-10 18:43 UTC, FrankIglesias requested changes

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/angular_icon.svg" alt="Angular logo"></img>
<img ... />

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/vue_icon.svg" alt="VueJS logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/elm_icon.svg" alt="Elm logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/polymer_icon.svg" alt="Polymer logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/rails_icon.png" alt="Rails logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/express_icon.svg" alt="NodeJS logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/aspnet_icon.png" alt="aspnet logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/django_icon.svg" alt="Django logo"></img>
same

2018-08-10 18:43 UTC, FrankIglesias commented on scss/titles.scss
> +  margin: 30px 10px 10px 10px;
margin: 30px 10px 10px;

2018-08-10 19:39 UTC, mikolaslorant commented
Already Corrected and pushed

2018-08-14 01:30 UTC, FrankIglesias requested changes

2018-08-14 01:30 UTC, FrankIglesias commented on index.html
> +        <img class="tech-logo" src="assets/images/angular_icon.svg" alt="Angular logo"/>
add space before slash

2018-08-14 01:30 UTC, FrankIglesias commented on scss/tech.scss
> +   &::before {
delete this space

2018-08-14 01:30 UTC, FrankIglesias commented on scss/tech.scss
> +  transition: left 0.5s ease, top 0.5s ease;
nest this hover inside the tech class

2018-08-14 01:30 UTC, FrankIglesias commented on scss/tech.scss
> +  transition: left 0.5s ease, top 0.5s ease;
`:hover::before`

2018-08-14 01:30 UTC, FrankIglesias commented on scss/titles.scss
> +  padding-bottom: 30px;
use shorthand for padding

2018-08-15 14:09 UTC, FrankIglesias approved these changes

2018-08-15 14:24 UTC, merged