Navbar and footer addition
wolox-training/ml-net-core pull request #4
Opened 2018-08-13 13:28 UTC by mikolaslorant

## Summary
-Added navbar 
-Added footer
-Added logos

## Screenshot

![footer](https://user-images.githubusercontent.com/28982362/44034468-89aa16c6-9ee3-11e8-8d26-52f37bd42a81.png)
![navbar](https://user-images.githubusercontent.com/28982362/44034469-89cdb446-9ee3-11e8-9ec8-a4a5917091f9.png)

## Trello cards
-Footer
-Navbar

2018-08-14 01:24 UTC, FrankIglesias requested changes

2018-08-14 01:24 UTC, FrankIglesias commented on index.html
> +      <img class="wlogo" src="assets/images/wolox_logo.svg"/>
add an alt

2018-08-14 01:24 UTC, FrankIglesias commented on index.html
> +          <img class="tech-logo" src="assets/images/react_icon.svg" alt="React logo"/>
space before slash

2018-08-14 01:24 UTC, FrankIglesias commented on index.html
> +          <img class="tech-logo" src="assets/images/angular_icon.svg" alt="Angular logo"/>
same

2018-08-14 01:24 UTC, FrankIglesias commented on scss/navbar.scss
> +  background-color: white;
use variable color

2018-08-14 01:24 UTC, FrankIglesias commented on scss/navbar.scss
> +  margin: 20px 10px auto 10px;
margin 20px auto 10px;

2018-08-15 12:51 UTC, mikolaslorant commented
Corrected requested changes

2018-08-15 14:09 UTC, FrankIglesias requested changes

2018-08-15 14:09 UTC, FrankIglesias commented on scss/footer.scss
> +  color: white;
use a variable color

2018-08-15 14:09 UTC, FrankIglesias commented on scss/navbar.scss
> +  position:fixed;
space after comma

2018-08-15 14:09 UTC, FrankIglesias commented on scss/navbar.scss
> +  float:right;
same

2018-08-15 14:29 UTC, mikolaslorant commented
Corrected new requested changes

2018-08-15 18:17 UTC, FrankIglesias requested changes

2018-08-15 18:17 UTC, FrankIglesias commented on scss/navbar.scss
> +  float: right;
mmmmm you can apply a flexbox property to the navbar to avoid this

2018-08-15 18:29 UTC, FrankIglesias approved these changes

2018-08-15 18:30 UTC, merged