Css grid layout
wolox-training/ml-net-core pull request #5
Opened 2018-08-13 16:01 UTC by mikolaslorant

## Summary

-added navbar shadow
-css tech component color change to white
-added css grid layout for tech component
## Screenshot

![css-grid](https://user-images.githubusercontent.com/28982362/44043275-d2553ff8-9ef8-11e8-9915-e8fb4fb8878b.png)

## Trello cards
-Rediseño de la página

2018-08-14 01:26 UTC, FrankIglesias requested changes

2018-08-14 01:26 UTC, FrankIglesias commented on scss/navbar.scss
> +  -webkit-box-shadow: 0px 6px 27px -7px rgba(0,0,0,0.55);
use variable color for the last param

2018-08-14 01:26 UTC, FrankIglesias commented on scss/tech.scss
> +
remove this line

2018-08-14 01:26 UTC, FrankIglesias commented
Excellent job

2018-08-15 12:54 UTC, mikolaslorant commented
Corrected requested changes.

2018-08-15 14:05 UTC, FrankIglesias approved these changes

2018-08-15 18:31 UTC, merged