Model, view, controller and  postgresql setup
wolox-training/ml-net-core pull request #8
Opened 2018-08-22 15:55 UTC by mikolaslorant

## Summary
-Model, view and controller added. 
-Added postgres configuration.

## Trello card
-MVC - Views
-MVC - Controllers
-MVC - Models

## Screenshot
![screenshot from 2018-08-22 12-54-16](https://user-images.githubusercontent.com/28982362/44475082-84a3a100-a60a-11e8-80b6-9cf32b5372fa.png)

2018-08-22 18:34 UTC, gussiciliano requested changes

2018-08-22 18:34 UTC, gussiciliano commented on src/Models/Movie.cs
> +        public int ID { get; set; }
change this for`Id`

2018-08-22 18:34 UTC, gussiciliano commented on src/Models/Movie.cs
> +}
add eof

2018-08-22 18:34 UTC, gussiciliano commented on src/Views/HelloWorld/index.cshtml
> +<p>Hello from our View Template!</p>
add eof

2018-08-22 18:34 UTC, gussiciliano commented on src/Views/HelloWorld/index.cshtml
> +
delete this empty line

2018-08-22 18:34 UTC, gussiciliano commented on src/Views/HelloWorld/Welcome.cshtml
> +
delete this empty line

2018-08-22 18:34 UTC, gussiciliano commented on src/Views/HelloWorld/Welcome.cshtml
> +</ul>
add eof

2018-08-22 18:34 UTC, gussiciliano commented on src/Controllers/HelloWorldController.cs
> +        public IActionResult Welcome(string name, int numTimes = 1)
remove the `int numTimes` :P

2018-08-22 18:34 UTC, gussiciliano commented on src/Views/HelloWorld/Welcome.cshtml
> +    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
delete this for

2018-08-22 19:38 UTC, mikolaslorant commented
Already corrected requested changes

2018-08-23 13:50 UTC, gussiciliano approved these changes

2018-08-24 12:16 UTC, merged